development: &sandbox
  api_keys:
    - token: 'AgAAAA**AQAAAA**aAAAAA**DDTSVw**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4GjDJWBpQ6dj6x9nY+seQ**1u0DAA**AAMAAA**fxWbZz6dEdimQ40t2WGBB6f9MOzn93Xv+TK7/wJUWO1idaEOO/DmHctY7Na6W+LiOgCEKxT6xcxbE+rCV/9TsAFnQThvzKCJQP/1/go6uCPCXEdtnJL6jnIaKr2wWVRQCRqzgcdb/9jxBcqg5MHY9W1fl3OQkDUkEst3svuZRd0XDNyaS+5FKlPSN7+Pb1UPLRJjsLpJlwmzgQxyUpLX8phuTdWDnDU5WJ/jgxCSC3+bAnb5ITIuypJHvCfFcdV+N4b080RMKsu3pBlGBFHgPwv+0SnhG+iuO++CHu+DvMXQtgF+1vq13Sd9xKat4Hvr1UqxFJ7OIMLF6Xx7lpXfIg8/NZJYPTSn6/cudGy7OzEhoFISn6t6HYbjKiT1IO1s6skFxlonomDe17EzTo/Yc1VPySk+sTh8Hnyc12pRN3eDbuSMoNs6oRdAjanBXQcle9KAslIZlDiQYStm2pDAw9bShGSG5OyVb/9d3irKs41T9iow23KiOhl7ABmAUdFzeLAtOesHmHLvLoetQZTEkxfPO9Y4KOSnA+SEk9jk4DLngPH+T1546y2Hmw4fueFnquk3xopzUXzUCSU/nXTPH4ivhAnM8c3ggAmLKaYu8mrZRPU1kT1Gr9qME56azeYtbwxCAUaL4XA8+kOf1vizx0DtAhHpfK+hXUK2vb7BNghGA6nNSGFqW2afPrev11tHl5b3Ud/DZvMkKomz/BfbyGXrb1FR7fMImSmTgkzvdooECdySP4xacQemKQxGoVGQ'
      devid: '<a036b866-4e0d-49de-b7f6-a45309064be2>'
      appid: '<BlakeGei-standard-SBX-5e6e394ea-29d730e6>'
      certid: '<SBX-e6e394ea763e-b466-4f1c-9f4e-f991>'

test:
  <<: *sandbox

production:
  api_keys:
    - token: '<YOUR LIVE AUTHENTICATION TOKEN>'
      devid: '<YOUR LIVE DEV ID>'
      appid: '<YOUR LIVE APP ID>'
      certid: '<YOUR LIVE CERT ID>'
